config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
  	validates :body, presence: true
  	has_one_attached :avatar, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all.with_attached_avatar
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(users_params)
		if @user.save
     		 redirect_to @user
   		else
    		render :new, status: :unprocessable_entity
    	end
	end

	def edit
		@user = User.find(params[:id])
	end
	

	def update
		@user = User.find(params[:id])

		if @user.update(users_params)
			redirect_to @user
		else
			render :edit, status: :unprocessable_entity
		end
	end
	

	def destroy
		byebug
		@user = User.find(params[:id])
		@user.destroy

		redirect_to root_path, status: :see_other
	end
	

	private

	def users_params
		params.require(:user).permit(:name, :body, :avatar)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageUploader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>
<body class="bg-light">
  <div class="container mt-5 bg-white">
    
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, class:"form-control"  %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body, class:"form-control" %>
  </div>

  <div>
    <%= form.label :Image %>
<%= form.file_field :avatar, class:"form-control" %>
  </div>

  <div class="mt-3">
    <%= form.submit  class:"btn btn-primary  btn-block"%>
    <%= link_to "Back" , root_path , class:"btn btn-success" %>

  </div>
<% end %>

</div>
</body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>
<body class="bg-light">
  <div class="container mt-5 bg-white">
    <h1>Edit user</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, class:"form-control"  %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body, class:"form-control" %>
  </div>

  <div>
    <%= form.label :Image %>
<%= form.file_field :avatar, class:"form-control" %>
  </div>

  <div class="mt-3">
    <%= form.submit  class:"btn btn-primary  btn-block"%>
    <%= link_to "Back" , root_path , class:"btn btn-success" %>

  </div>
<% end %>

</div>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>
<body class="bg-light">

  <div class="container bg-white mt-5">

    <h1 >User lists</h1>
    <%= link_to "New user", new_user_path , class:"btn btn-warning" %>
    <table class="table">
     
  <thead>
    <tr>
      
      <th scope="col">Name</th>
      <th scope="col">Role</th>
      <th scope="col"></th>
      
    </tr>
  </thead>
  <tbody>
     <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td> <%= link_to user.body, user %></td>
      <td><%= image_tag user.avatar, style: "width: 250px; display: block" %></td>
      <td> <%= link_to "show", user , class:"btn btn-primary"%></td>

    </tr>
  </tbody>
  <% end %>
</table>


</div>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>
<body class="bg-light">
  <div class="container mt-5 bg-white">
    <h1>New User </h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, class:"form-control"  %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body, class:"form-control" %>
  </div>

  <div>
    <%= form.label :Image %>
<%= form.file_field :avatar, class:"form-control" %>
  </div>

  <div class="mt-3">
    <%= form.submit  class:"btn btn-primary  btn-block"%>
    <%= link_to "Back" , root_path , class:"btn btn-success" %>

  </div>
<% end %>

</div>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>
<body class="bg-light">
  <div class="container mt-4 ">
  <div class="card" style="width: 500px; ">
  <%= image_tag (@user.avatar), width:"500px" ,height:"500px" if @user.avatar %>
  <div class="card-body text-center">
    <h5 class="card-title"><%= @user.name %></h5>
    <p class="card-text"><%= @user.body %></p>
    <%= link_to "Edit", edit_user_path(@user), class:"btn btn-primary" %></li>
  <%= link_to "Destroy", user_path(@user),class:"btn btn-primary", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
   <%= link_to "Back" , root_path , class:"btn btn-warning" %>
  </div>
</div>  
  </div>


</body>
</html>